### ISSUE TITLE
VS2017现在编译不通过了，年久失修？

### ISSUE THREAD

**Issue by xiaocjnu** [hjk41/tinyrpc#5]
连asio工程下，detail文件夹都没有了

**Comment by hjk41** [comment]
asio是个submodule，你得在tinyrpc目录下运行git submodule update --init才能把asio给clone下来

**Comment by xiaocjnu** [comment]
问题是asio目录下没有detail目录，代码中用到了




| |
xiaocjnu
邮箱：xiaocjnu@163.com
|

Signature is customized by Netease Mail Master

在2019年03月09日 19:56，Chuntao Hong 写道：
asio是个submodule，你得在tinyrpc目录下运行git submodule update --init才能把asio给clone下来

**Comment by hjk41** [comment]
正常的话应该有tinyrpc/tinyrpc/asio/asio/include/asio/detail

**Comment by xiaocjnu** [comment]
有的，那就是git上的sln文件有问题




| |
xiaocjnu
邮箱：xiaocjnu@163.com
|

Signature is customized by Netease Mail Master

在2019年03月09日 22:32，Chuntao Hong 写道：
正常的话应该有tinyrpc/tinyrpc/asio/asio/include/asio/detail

**Comment by hjk41** [comment]
你是不是选的x86编译？Platform(平台)得选x64，x86的编译选项不行。我应该在sln里把x86都删了 :-P

**Comment by hjk41** [comment]
删掉了，你再pull一下应该就只有x64的platform了

**Comment by xiaocjnu** [comment]
我明天试一下，谢谢




| |
xiaocjnu
邮箱：xiaocjnu@163.com
|

Signature is customized by Netease Mail Master

在2019年03月09日 22:43，Chuntao Hong 写道：
删掉了，你再pull一下应该就只有x64的platform了
